<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>net.mguenther.kafka</groupId>
    <artifactId>kafka-junit-parent</artifactId>
    <packaging>pom</packaging>
    <version>3.7.0-SNAPSHOT</version>
    <name>Kafka for JUnit (Parent)</name>
    <description>Parent POM for Kafka for JUnit and Kafka Browser</description>
    <url>https://mguenther.github.io/kafka-junit</url>

    <modules>
        <module>kafka-junit</module>
        <module>kafka-browser</module>
    </modules>

    <developers>
        <developer>
            <name>Markus Günther</name>
            <email>mail@mguenther.net</email>
            <url>https://www.mguenther.net</url>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:git://github.com/mguenther/kafka-junit.git</connection>
        <developerConnection>scm:git:git://github.com/mguenther/kafka-junit.git</developerConnection>
        <url>https://github.com/mguenther/kafka-junit/tree/master</url>
    </scm>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <kafka.version>3.6.1</kafka.version>
        <slf4j.version>1.7.36</slf4j.version>
        <lombok.version>1.18.30</lombok.version>
    </properties>

    <repositories>
        <repository>
            <id>confluent</id>
            <name>Confluent Release Repository</name>
            <url>http://packages.confluent.io/maven/</url>
        </repository>
    </repositories>

</project>
